In [ ]:
! pip install numpy

  Using cached numpy-2.3.5-cp313-cp313-win_amd64.whl.metadata (60 kB)
Using cached numpy-2.3.5-cp313-cp313-win_amd64.whl (12.8 MB)



[notice] A new release of pip is available: 24.3.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [1]:
import numpy as np

In [6]:
list_array = np.array([1, 2, 3, 4, 8])
print("Из списка:", list_array)

matrix_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D массив:")
print(matrix_2d)

zeros_arr = np.zeros(5)
print("Zeros:", zeros_arr)

ones_arr = np.ones((2, 3))
print("Ones 2x3:")
print(ones_arr)
range_arr = np.arange(0, 10, 2)
print("Arrange 0-10 step2:", range_arr)

linspace_arr = np.linspace(0, 1, 5)
print("Linspace 0-1, 5 точек:", linspace_arr)

Из списка: [1 2 3 4 8]
2D массив:
[[1 2 3]
 [4 5 6]]
Zeros: [0. 0. 0. 0. 0.]
Ones 2x3:
[[1. 1. 1.]
 [1. 1. 1.]]
Arrange 0-10 step2: [0 2 4 6 8]
Linspace 0-1, 5 точек: [0.   0.25 0.5  0.75 1.  ]


In [7]:
print("Форма matrix_2d:", matrix_2d.shape)
print("Тип данных matrix_2d:", matrix_2d.dtype)
print("Размерность:", matrix_2d.ndim)
print("Всего элементов:", matrix_2d.size)

Форма matrix_2d: (2, 3)
Тип данных matrix_2d: int64
Размерность: 2
Всего элементов: 6


In [8]:
data = np.array([10, 20, 30, 40, 50, 60, 75])
print("Исходный массив:", data)
print("data[0]:", data[0])
print("data[-1]:", data[-1])
print("data[1:4]:", data[1:4])
print("data[::2]:", data[::2])
print("data[3:]:", data[3:])

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Матрица 3x3:")
print(matrix)
print("matrix[1,2]:", matrix[1,2])
print("matrix[0]:", matrix[0])
print("matrix[:,1]:", matrix[:,1])
print("matrix[1:,:2]:")
print(matrix[1:,:2])

Исходный массив: [10 20 30 40 50 60 75]
data[0]: 10
data[-1]: 75
data[1:4]: [20 30 40]
data[::2]: [10 30 50 75]
data[3:]: [40 50 60 75]
Матрица 3x3:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
matrix[1,2]: 6
matrix[0]: [1 2 3]
matrix[:,1]: [2 5 8]
matrix[1:,:2]:
[[4 5]
 [7 8]]


In [9]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
print("a =", a)
print("b =", b)
print("a + b =", a + b)
print("a * b =", a * b)
print("b - a =", b - a)
print("a * 2 =", a * 2)
print("a ** 2 =", a ** 2)

a = [1 2 3 4]
b = [5 6 7 8]
a + b = [ 6  8 10 12]
a * b = [ 5 12 21 32]
b - a = [4 4 4 4]
a * 2 = [2 4 6 8]
a ** 2 = [ 1  4  9 16]


In [10]:
stats_data = np.array([2.5, 1.8, 3.2, 4.1, 2.9, 3.8])
print("Данные:", stats_data)
print("Среднее:", np.mean(stats_data))
print("Медиана:", np.median(stats_data))
print("Стандартное отклонение:", np.std(stats_data))
print("Минимум:", np.min(stats_data))
print("Максимум:", np.max(stats_data))
print("Сумма:", np.sum(stats_data))
print("Индекс максимума:", np.argmax(stats_data))

matrix_stats = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Матрица для статистики:")
print(matrix_stats)
print("Среднее по столбцам:", np.mean(matrix_stats, axis=0))
print("Сумма по строкам:", np.sum(matrix_stats, axis=1))

Данные: [2.5 1.8 3.2 4.1 2.9 3.8]
Среднее: 3.0500000000000003
Медиана: 3.05
Стандартное отклонение: 0.7719024117939606
Минимум: 1.8
Максимум: 4.1
Сумма: 18.3
Индекс максимума: 3
Матрица для статистики:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Среднее по столбцам: [4. 5. 6.]
Сумма по строкам: [ 6 15 24]
